---
- name: Create user 
  hosts: dbserver
  tasks:
    - name: User creation
      user:
        name: Ravi
        password: intelliqit
        comment: "A normal user"
        home: /tmp/Ravi
        uid: 2000
        shell: /bin/bash
...
